services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azuretelemetry-azurite
    restart: always
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 -l /data"

  api:
    build:
      context: .
      dockerfile: AzureTelemetry.Api/Dockerfile
    container_name: azuretelemetry-api
    depends_on:
      - azurite
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true;"

  worker:
    build:
      context: .
      dockerfile: AzureTelemetry.Worker/Dockerfile
    container_name: azuretelemetry-worker
    depends_on:
      - azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true;"
